default_platform(:android)

platform :android do
  desc "Upload metadata, screenshots, and images to Google Play Store"
  lane :upload_metadata do
    upload_to_play_store(
      track: "internal",
      version_code: 3,
      release_status: "draft",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
      sync_image_upload: true,
      changes_not_sent_for_review: true
    )
  end

  desc "Upload only images and screenshots"
  lane :upload_images do
    upload_to_play_store(
      track: "internal",
      version_code: 3,
      release_status: "draft",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      sync_image_upload: true,
      changes_not_sent_for_review: true
    )
  end

  desc "Build and upload AAB to internal testing"
  lane :beta do
    sh("cd .. && ./gradlew :app:bundleRelease")
    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Build and upload AAB to production"
  lane :production do
    sh("cd .. && ./gradlew :app:bundleRelease")
    upload_to_play_store(
      track: "production",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Promote internal to production"
  lane :promote do
    upload_to_play_store(
      track: "internal",
      track_promote_to: "production",
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
